/**
 * A FAQs page.
 */

import { H1 as Heading, Paragraph2 as Paragraph } from "baseui/typography";
import { Accordion, Panel } from "baseui/accordion";

import ScreenContainer from "@/components/ScreenContainer";
import Layout from "@/components/Layout";
import Highlight from "@/components/Highlight";
import Link from "@/components/Link";
import * as routes from "@/routes";

const Faq = () => {
	return (
		<Layout>
			<ScreenContainer id="callsesh-faq">
				<Heading>Frequently Asked Questions</Heading>
				<div>
					<Accordion
						overrides={{
							Content: {
								style: {
									backgroundColor: "rgb(250, 250, 250)"
								},
								props: {
									className: "accordion-panel-content"
								}
							}
						}}
					>
						<Panel title="How do I sign up?">
							<Paragraph>
								To create an account, click{" "}
								<Highlight>&quot;Get Started&quot;</Highlight> on the Callsesh
								home page or <Highlight>&quot;Sign Up&quot;</Highlight>. Provide
								the phone number you will use to make and take calls. You will
								receive a text message with a verification code. Enter this
								verification code to sign up and log in to your account.
							</Paragraph>
							<Paragraph>
								Once you authorise your account, you will land on our
								registration form where you can provide the information to build
								your profile.
							</Paragraph>
						</Panel>
						<Panel title="How can I make a call to an operator?">
							<Paragraph>
								<Highlight>Operator Call Links</Highlight> will be shared by
								Operators to their website, Social Profiles and anywhere else on
								the internet. Use these Call links to visit the Operator&apos;s
								profile and use the Call button to make a call. An Operator must
								be <Highlight>live</Highlight> to accept calls.
							</Paragraph>
						</Panel>
						<Panel title="How do I know I am receiving a call?">
							<Paragraph>
								You will receive a text message notifying you of an incoming
								call and the caller name.
							</Paragraph>
						</Panel>
						<Panel title="Is my personal information secure?">
							<Paragraph>
								Your profile information is shared on your Call page, but your
								personal contact information will never be shared with any third
								party, or any other user on Callsesh.
							</Paragraph>
						</Panel>
						<Panel title="Can a caller or operator see my phone number?">
							<Paragraph>
								No. As an Operator, callers can only call you through your Call
								link URL generated by Callsesh. As a Caller, you will be sent an
								SMS with a special phone number to call to connect your
								Operator. We do not reveal or share your personal contact phone
								number to other users.
							</Paragraph>
						</Panel>
						<Panel title="Are there any fees?">
							<Paragraph>
								There are no sign up or subscription fees. There is a 20% call
								fee on all call transactions. This means we only get paid when
								you do!
							</Paragraph>
						</Panel>
						<Panel title="How do I get paid?">
							<Paragraph>
								You can link a bank account or other payout method of choice to
								receive direct payments. Pending payouts are paid by us on the
								first day of each calendar month, however, depending on your
								region, you can connect your Bank Account with Stripe using the{" "}
								<Highlight>&quot;Manage/Setup Payouts&quot;</Highlight> to be
								paid every few business days.
							</Paragraph>
						</Panel>
						<Panel title="How do I see my payouts?">
							<Paragraph>
								If you see a &quot;Manage/Setup Payouts&quot; button on your
								Operator dashboard, this can be used to view your upcoming
								payouts, otherwise you can contact Callsesh support directly for
								updates on outgoing payouts, or a payouts summary.
							</Paragraph>
						</Panel>
						<Panel title="Can I earn money by referring people?">
							<Paragraph>
								Yes. You can earn 5% of your referred operator&apos;s call
								transactions. All you need to do is share the referral invite
								link (in your dashboard) to your friends. Once they sign up and
								start receiving calls, you will begin to earn!{" "}
								<Link href={routes.page.referrals}>
									Learn more about referrals
								</Link>
							</Paragraph>
						</Panel>
						<Panel title="How do I leave feedback?">
							<Paragraph>
								Contact Callsesh Support and leave us a comment. We&apos;re
								eager to hear more from you!
							</Paragraph>
						</Panel>
						<Panel title="Where is Callsesh based?">
							<Paragraph>
								We are based in Sydney, Australia but we service users around
								the globe!
							</Paragraph>
						</Panel>
					</Accordion>
				</div>
			</ScreenContainer>
		</Layout>
	);
};

export default Faq;
