service: call-session-manager

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
frameworkVersion: ">=1.28.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs12.x
  region: ${opt:region, 'us-east-2'}
  memorySize: 256
  timeout: 30
  stage: ${opt:stage, 'dev'}
  environment:
    NODE_ENV:
      ${self:custom.nodeEnv.${opt:stage, self:provider.stage}, 'development'}

package:
  exclude:
    - bin/**
    - cache/**
    - debug/**
    - logs/**
    - test/**

plugins:
  - serverless-plugin-common-excludes
  - serverless-step-functions
  - serverless-pseudo-parameters
  - serverless-offline
  - serverless-webpack

custom:
  nodeEnv:
    dev: development
    prod: production
  serverless-offline:
    port: 9000
  webpack:
    webpackConfig: "webpack.config.js"

functions:
  end:
    handler: src/index.end
    description: Run call session end events if expired

stepFunctions:
  validate: true
  stateMachines:
    CallSessionEnder: ${file(resources/state-machines/ender.yml)}

resources:
  - ${file(resources/iam.yml)}
  - ${file(resources/sns.yml)}
  - ${file(resources/outputs.yml)}
