Resources:
  CallseshWorkflowsNotificationsTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: "Callsesh Workflows Notifications"
      TopicName:
        CallseshWorkflowsNotifications-${opt:stage, self:provider.stage}
      Subscription:
        - Endpoint: "ryan@callsesh.com"
          Protocol: email
